python3 main_pretrain.py \
    --dataset cifar10 \
    --backbone resnet18 \
    --data_dir ./dataset \
    --max_epochs 400 \
    --gpus 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.4 \
    --classifier_lr 3 \
    --weight_decay 1e-4 \
    --batch_size 256 \
    --num_workers 20 \
    --crop_size 32 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.4 \
    --hue 0.1 \
    --gaussian_prob 0.0 0.0 \
    --crop_size 32 \
    --num_crops_per_aug 1 1 \
    --name supcon-cifar10 \
    --project solo-learn \
    --entity unitn-mhug \
    --csv \
    --save_checkpoint \
    --method supcon \
    --temperature 0.2 \
    --proj_hidden_dim 2048 \
    --proj_output_dim 256 \
    --checkpoint_frequency=20 \
    --corrupt ${1:-ori} \
