python3 main_pretrain.py \
    --dataset $1 \
    --backbone resnet18 \
    --data_dir ./datasets \
    --max_epochs 200 \
    --gpus 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 1.0 \
    --classifier_lr 0.1 \
    --weight_decay 1e-5 \
    --batch_size 256 \
    --num_workers 12 \
    --brightness 0. --contrast 0. --saturation 0. --hue 0. --color_jitter_prob 0. \
    --gray_scale_prob 0. \
    --horizontal_flip_prob 0. \
    --gaussian_prob 0. 0. \
    --solarization_prob 0. 0. \
    --crop_size 32 --min_scale 1.0 --max_scale 1.0 \
    --num_crops_per_aug 1 1 \
    --name byol-noaug-$1 \
    --project solo-learn \
    --entity unitn-mhug \
    --save_checkpoint \
    --method byol \
    --proj_output_dim 256 \
    --proj_hidden_dim 4096 \
    --pred_hidden_dim 4096 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 1.0 \
    --momentum_classifier \
    --csv \
    --checkpoint_frequency=50 \
    --corrupt ${2:-ori} \
    --knn_eval --knn_k=200

# --wandb
