python3 main_pretrain.py \
    --dataset $1 \
    --backbone resnet18 \
    --data_dir ./datasets \
    --max_epochs 200 \
    --gpus 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --classifier_lr 0.3 \
    --weight_decay 1e-4 \
    --batch_size 256 \
    --num_workers 6 \
    --brightness 0. --contrast 0. --saturation 0. --hue 0. --color_jitter_prob 0. \
    --gray_scale_prob 0. \
    --horizontal_flip_prob 0. \
    --gaussian_prob 0. 0. \
    --solarization_prob 0. 0. \
    --crop_size 32 --min_scale 1.0 --max_scale 1.0 \
    --num_crops_per_aug 1 1 \
    --name mocov2plus-noaug-$1 \
    --project solo-learn \
    --entity unitn-mhug \
    --save_checkpoint \
    --method mocov2plus \
    --proj_hidden_dim 2048 \
    --queue_size 32768 \
    --temperature 0.2 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 0.999 \
    --momentum_classifier \
    --csv \
    --checkpoint_frequency=50 \
    --corrupt ${2:-ori} \
    --knn_eval --knn_k=200
